### ISSUE TITLE
Develop a web crawler to extract data about unknown words or proper nouns

### ISSUE THREAD

**Issue by ovidiupw** [ovidiupw/ChatbotTextProcessing#11]
### Description
__Input:__ A string representing an expression (e.g. "borobudur", "1+1", "WYSIWYG")
__Output:__ A list containing objects. Each object will contain a string with relevant information about the searched expression (e.g. named "description") whose max length should not be higher than 4 kilobytes. The object should also contain the URL  where the "description" was found.

### Suggestions
Maybe use https://duckduckgo.com/ API.

**Comment by ovidiupw** [comment]
Closing as completed.

**Comment by alxrusu** [comment]
crawler.py - python script for web crawling.

modules used:
BeautifulSoup - to parse and transform the html into plaintext.
google - to get google search results on a topic in order to use them as seeds for in-depth page crawling.
be - to obtain specific information from webpages (all the url's found on the page)
json - for the duckduckgo api results.

The script performs a google search on the term passed and saves the url's found within the first 10 (or the number given) results. 
Recursively searches the pages previously saved for phrases containing the term given and returns a list of dictionaries with the "description" and "source" keys.
