### ISSUE TITLE
Introduce annotations that implement anaphora resolution

### ISSUE THREAD

**Issue by ovidiupw** [ovidiupw/ChatbotTextProcessing#4]
E.g. for \<word>she\</word>, if "she" refers to "Maria", then introduce attribute ref="Maria" inside the \<word> tag: \<word ref="Maria" /> she \</word>

**Comment by adrianbutnaru4** [comment]
Made a gender classifier for singular proper nouns (English first names) using a Naive Bayes classifier from the NLTK platform and started a number and gender classifier for pronouns.

**Comment by adrianbutnaru4** [comment]
Used the nltk anaphora solver to add annotations to pronouns.
TODO: improve drt grammar:
* https://gist.github.com/adrianbutnaru4/c5ab2446302c22643886889b2747e39e

**Comment by adrianbutnaru4** [comment]
Improved the grammar by adding a list of popular common and proper nouns used in the English language. Also added tranzitive and intranzitive verbs that are used when finding the anaphora. The 'resolve_anaphora' method from the nltk libraby returns matched sentences and a list of words (mostly nouns or pronouns) for each pronoun (only basic personal are covered). Those words are found in a sintactic manner, not a semantic one, so the list must be further processed in order to find the right word that can replace the pronoun. The string returned by the 'resolve_anaphora' method is processed using regular expressions and other tokenization methods.

Module used for anaphora resolution: http://www.nltk.org/
